name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Usa la versión LTS recomendada, o ajusta según tus necesidades.

      - name: Install dependencies
        run: npm install --legacy-peer-deps  # Usa --legacy-peer-deps si tienes conflictos de dependencias

      - name: Build and test
        run: npm run build
